[mypy]
python_version = 3.12
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = True

[mypy-apps.api.*]
ignore_missing_imports = True

[mypy-apps.worker.*]
ignore_missing_imports = True

[mypy-packages.core.*]
ignore_missing_imports = True
