"""Initial schema

Revision ID: 61740c862ce0
Revises:
Create Date: 2025-12-31 18:21:46.796370

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "61740c862ce0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clusters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("keywords", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("idea_count", sa.Integer(), nullable=False),
        sa.Column("avg_sentiment", sa.Float(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("trend_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_clusters_idea_count_desc",
        "clusters",
        [sa.literal_column("idea_count DESC")],
        unique=False,
    )
    op.create_index(
        "idx_clusters_trend_score_desc",
        "clusters",
        [sa.literal_column("trend_score DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_clusters_created_at"), "clusters", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_clusters_idea_count"), "clusters", ["idea_count"], unique=False
    )
    op.create_index(
        op.f("ix_clusters_quality_score"), "clusters", ["quality_score"], unique=False
    )
    op.create_index(
        op.f("ix_clusters_trend_score"), "clusters", ["trend_score"], unique=False
    )
    op.create_table(
        "raw_posts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("url_hash", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("raw_sentiment", sa.Float(), nullable=True),
        sa.Column("is_processed", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_raw_posts_is_processed_false",
        "raw_posts",
        ["is_processed"],
        unique=False,
        postgresql_where=sa.text("is_processed = false"),
    )
    op.create_index(
        "idx_raw_posts_published_at_desc",
        "raw_posts",
        [sa.literal_column("published_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_raw_posts_source_metadata",
        "raw_posts",
        ["source_metadata"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_raw_posts_is_processed"), "raw_posts", ["is_processed"], unique=False
    )
    op.create_index(op.f("ix_raw_posts_source"), "raw_posts", ["source"], unique=False)
    op.create_index(op.f("ix_raw_posts_url"), "raw_posts", ["url"], unique=True)
    op.create_index(
        op.f("ix_raw_posts_url_hash"), "raw_posts", ["url_hash"], unique=False
    )
    op.create_table(
        "idea_candidates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raw_post_id", sa.UUID(), nullable=False),
        sa.Column("problem_statement", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("sentiment", sa.String(length=20), nullable=False),
        sa.Column("sentiment_score", sa.Float(), nullable=False),
        sa.Column("emotions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("domain", sa.String(length=100), nullable=True),
        sa.Column("features_mentioned", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("is_valid", sa.Boolean(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["raw_post_id"], ["raw_posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_idea_candidates_is_valid_true",
        "idea_candidates",
        ["is_valid"],
        unique=False,
        postgresql_where=sa.text("is_valid = true"),
    )
    op.create_index(
        "idx_idea_candidates_problem_statement_fts",
        "idea_candidates",
        ["problem_statement"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"problem_statement": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_idea_candidates_quality_score_desc",
        "idea_candidates",
        [sa.literal_column("quality_score DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_idea_candidates_domain"), "idea_candidates", ["domain"], unique=False
    )
    op.create_index(
        op.f("ix_idea_candidates_is_valid"),
        "idea_candidates",
        ["is_valid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_idea_candidates_quality_score"),
        "idea_candidates",
        ["quality_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_idea_candidates_raw_post_id"),
        "idea_candidates",
        ["raw_post_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_idea_candidates_sentiment"),
        "idea_candidates",
        ["sentiment"],
        unique=False,
    )
    op.create_table(
        "cluster_memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cluster_id", sa.UUID(), nullable=False),
        sa.Column("idea_id", sa.UUID(), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.Column("is_representative", sa.Boolean(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["cluster_id"], ["clusters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["idea_id"], ["idea_candidates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_cluster_memberships_is_representative",
        "cluster_memberships",
        ["cluster_id", "is_representative"],
        unique=False,
        postgresql_where=sa.text("is_representative = true"),
    )
    op.create_index(
        op.f("ix_cluster_memberships_cluster_id"),
        "cluster_memberships",
        ["cluster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cluster_memberships_idea_id"),
        "cluster_memberships",
        ["idea_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cluster_memberships_is_representative"),
        "cluster_memberships",
        ["is_representative"],
        unique=False,
    )
    op.create_index(
        "uq_cluster_idea", "cluster_memberships", ["cluster_id", "idea_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_cluster_idea", table_name="cluster_memberships")
    op.drop_index(
        op.f("ix_cluster_memberships_is_representative"),
        table_name="cluster_memberships",
    )
    op.drop_index(
        op.f("ix_cluster_memberships_idea_id"), table_name="cluster_memberships"
    )
    op.drop_index(
        op.f("ix_cluster_memberships_cluster_id"), table_name="cluster_memberships"
    )
    op.drop_index(
        "idx_cluster_memberships_is_representative",
        table_name="cluster_memberships",
        postgresql_where=sa.text("is_representative = true"),
    )
    op.drop_table("cluster_memberships")
    op.drop_index(op.f("ix_idea_candidates_sentiment"), table_name="idea_candidates")
    op.drop_index(op.f("ix_idea_candidates_raw_post_id"), table_name="idea_candidates")
    op.drop_index(
        op.f("ix_idea_candidates_quality_score"), table_name="idea_candidates"
    )
    op.drop_index(op.f("ix_idea_candidates_is_valid"), table_name="idea_candidates")
    op.drop_index(op.f("ix_idea_candidates_domain"), table_name="idea_candidates")
    op.drop_index(
        "idx_idea_candidates_quality_score_desc", table_name="idea_candidates"
    )
    op.drop_index(
        "idx_idea_candidates_problem_statement_fts",
        table_name="idea_candidates",
        postgresql_using="gin",
        postgresql_ops={"problem_statement": "gin_trgm_ops"},
    )
    op.drop_index(
        "idx_idea_candidates_is_valid_true",
        table_name="idea_candidates",
        postgresql_where=sa.text("is_valid = true"),
    )
    op.drop_table("idea_candidates")
    op.drop_index(op.f("ix_raw_posts_url_hash"), table_name="raw_posts")
    op.drop_index(op.f("ix_raw_posts_url"), table_name="raw_posts")
    op.drop_index(op.f("ix_raw_posts_source"), table_name="raw_posts")
    op.drop_index(op.f("ix_raw_posts_is_processed"), table_name="raw_posts")
    op.drop_index(
        "idx_raw_posts_source_metadata", table_name="raw_posts", postgresql_using="gin"
    )
    op.drop_index("idx_raw_posts_published_at_desc", table_name="raw_posts")
    op.drop_index(
        "idx_raw_posts_is_processed_false",
        table_name="raw_posts",
        postgresql_where=sa.text("is_processed = false"),
    )
    op.drop_table("raw_posts")
    op.drop_index(op.f("ix_clusters_trend_score"), table_name="clusters")
    op.drop_index(op.f("ix_clusters_quality_score"), table_name="clusters")
    op.drop_index(op.f("ix_clusters_idea_count"), table_name="clusters")
    op.drop_index(op.f("ix_clusters_created_at"), table_name="clusters")
    op.drop_index("idx_clusters_trend_score_desc", table_name="clusters")
    op.drop_index("idx_clusters_idea_count_desc", table_name="clusters")
    op.drop_table("clusters")
    # ### end Alembic commands ###
