"""add vector columns

Revision ID: f6e39222109b
Revises: 61740c862ce0
Create Date: 2026-01-02 15:50:09.379285

"""

from collections.abc import Sequence
from typing import Union

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6e39222109b"
down_revision: str | Sequence[str] | None = "61740c862ce0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure vector extension exists
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clusters",
        sa.Column(
            "cluster_vector", pgvector.sqlalchemy.Vector(dim=1536), nullable=True
        ),
    )
    op.add_column(
        "idea_candidates",
        sa.Column("idea_vector", pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    )
    op.create_index(
        op.f("ix_raw_posts_fetched_at"), "raw_posts", ["fetched_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_raw_posts_fetched_at"), table_name="raw_posts")
    op.drop_column("idea_candidates", "idea_vector")
    op.drop_column("clusters", "cluster_vector")
    # ### end Alembic commands ###
