#!/usr/bin/env python3
"""
Expand sample_posts.json with 80+ more high-quality app idea posts.
Covers 15+ domains with realistic metadata.
"""

import json
from datetime import datetime, timedelta

# Additional posts to append (80 new posts)
new_posts = [
    # Developer Tools (8 posts)
    {
        "url": "https://news.ycombinator.com/item?id=39902001",
        "title": "I wish there was a Git client that visualizes code changes in 3D over time",
        "content": "Understanding code evolution through text diffs is limiting. I want to see my codebase as a 3D tree structure where branches grow, merge, and evolve. Visualize complexity hotspots, contributor impact, and architecture drift.",
        "source": "hackernews",
        "author": "code_visualizer",
        "published_at": (datetime.now() - timedelta(days=5)).isoformat() + "Z",
        "metadata": {
            "upvotes": 312,
            "comments": 87,
            "domain": "developer-tools",
            "tags": ["git", "visualization", "code-review", "3d", "devtools"],
        },
    },
    {
        "url": "https://reddit.com/r/webdev/comments/xyz789",
        "title": "Need an AI-powered code reviewer that learns from my team's style guide",
        "content": "Generic linters don't understand our company's specific conventions. I want an AI that reviews PRs, catches logic bugs, suggests refactors, and enforces our custom patterns. Train it on our best PRs.",
        "source": "reddit",
        "author": "tech_lead_dev",
        "published_at": (datetime.now() - timedelta(days=7)).isoformat() + "Z",
        "metadata": {
            "upvotes": 267,
            "comments": 94,
            "domain": "developer-tools",
            "subreddit": "webdev",
            "tags": ["ai", "code-review", "automation", "style-guide", "devtools"],
        },
    },
    {
        "url": "https://twitter.com/dev_lead/status/1234570001",
        "title": "Why isn't there a tool that automatically documents API changes between versions?",
        "content": "Maintaining changelogs is tedious and error-prone. Give me a tool that diffs my OpenAPI specs, generates human-readable release notes, and creates migration guides automatically. Semantic versioning built-in.",
        "source": "twitter",
        "author": "api_architect",
        "published_at": (datetime.now() - timedelta(days=10)).isoformat() + "Z",
        "metadata": {
            "likes": 189,
            "retweets": 56,
            "domain": "developer-tools",
            "tags": ["api", "documentation", "versioning", "automation", "devtools"],
        },
    },
    {
        "url": "https://dev.to/article123",
        "title": "I need a database query analyzer that suggests indexes based on production traffic",
        "content": "Slow queries plague every app. I want a tool that monitors real production queries, identifies patterns, suggests optimal indexes, and shows expected performance gains. Automated database optimization.",
        "source": "dev.to",
        "author": "dba_expert",
        "published_at": (datetime.now() - timedelta(days=12)).isoformat() + "Z",
        "metadata": {
            "reactions": 145,
            "comments": 34,
            "domain": "developer-tools",
            "tags": ["database", "performance", "optimization", "indexing", "devtools"],
        },
    },
    {
        "url": "https://news.ycombinator.com/item?id=39902002",
        "title": "Someone build a CLI tool that converts natural language to shell commands",
        "content": "I forget complex commands like tar, ffmpeg, and awk syntax constantly. I want to type 'extract this tar.gz file' and get the right command with explanations. AI-powered shell assistant.",
        "source": "hackernews",
        "author": "cli_user",
        "published_at": (datetime.now() - timedelta(days=15)).isoformat() + "Z",
        "metadata": {
            "upvotes": 401,
            "comments": 156,
            "domain": "developer-tools",
            "tags": ["cli", "ai", "natural-language", "automation", "productivity"],
        },
    },
    {
        "url": "https://reddit.com/r/programming/comments/abc456",
        "title": "Need a debugging tool that records and replays HTTP requests in development",
        "content": "Bugs happen in specific request sequences that are hard to reproduce. I want a proxy that records all HTTP traffic, lets me replay it step-by-step, modify requests, and see what breaks. Time-travel debugging for APIs.",
        "source": "reddit",
        "author": "backend_dev",
        "published_at": (datetime.now() - timedelta(days=18)).isoformat() + "Z",
        "metadata": {
            "upvotes": 178,
            "comments": 42,
            "domain": "developer-tools",
            "subreddit": "programming",
            "tags": ["debugging", "http", "api", "testing", "devtools"],
        },
    },
    {
        "url": "https://twitter.com/devops_eng/status/1234570002",
        "title": "Why isn't there a visual Docker Compose editor with live validation?",
        "content": "Writing docker-compose.yml by hand is error-prone. I want a GUI where I drag-and-drop services, define networks/volumes visually, and get real-time validation. Export to YAML when done. Kubernetes too!",
        "source": "twitter",
        "author": "devops_engineer",
        "published_at": (datetime.now() - timedelta(days=21)).isoformat() + "Z",
        "metadata": {
            "likes": 234,
            "retweets": 78,
            "domain": "developer-tools",
            "tags": ["docker", "devops", "visualization", "containers", "kubernetes"],
        },
    },
    {
        "url": "https://news.ycombinator.com/item?id=39902003",
        "title": "I wish there was a tool that automatically generates integration tests from OpenAPI specs",
        "content": "Writing integration tests manually is tedious. My API spec has all the info needed: endpoints, schemas, validation rules. Auto-generate test suites with property-based testing. Update tests when specs change.",
        "source": "hackernews",
        "author": "qa_automation",
        "published_at": (datetime.now() - timedelta(days=24)).isoformat() + "Z",
        "metadata": {
            "upvotes": 289,
            "comments": 71,
            "domain": "developer-tools",
            "tags": [
                "testing",
                "openapi",
                "automation",
                "integration-tests",
                "devtools",
            ],
        },
    },
    # Gaming (6 posts)
    {
        "url": "https://reddit.com/r/gaming/comments/game001",
        "title": "Need an app that tracks my gaming backlog and suggests what to play next based on mood",
        "content": "I have 200+ unplayed games. I want an app that knows my mood (relaxing vs challenging), available time (30 min vs 3 hours), and current interests. Recommend from my backlog, track completion rates.",
        "source": "reddit",
        "author": "gamer_backlog",
        "published_at": (datetime.now() - timedelta(days=6)).isoformat() + "Z",
        "metadata": {
            "upvotes": 445,
            "comments": 189,
            "domain": "gaming",
            "subreddit": "gaming",
            "tags": [
                "gaming",
                "recommendation",
                "mood-tracking",
                "backlog",
                "organization",
            ],
        },
    },
    {
        "url": "https://twitter.com/esports_fan/status/1234570003",
        "title": "Why isn't there a tournament bracket creator with live score updates and stream integration?",
        "content": "Running local esports tournaments is a pain. I need: bracket generation, score tracking, automatic tweet updates, Twitch stream embeds, player profiles. All-in-one tournament management.",
        "source": "twitter",
        "author": "esports_organizer",
        "published_at": (datetime.now() - timedelta(days=9)).isoformat() + "Z",
        "metadata": {
            "likes": 312,
            "retweets": 94,
            "domain": "gaming",
            "tags": [
                "esports",
                "tournaments",
                "streaming",
                "competition",
                "organization",
            ],
        },
    },
    {
        "url": "https://news.ycombinator.com/item?id=39902004",
        "title": "Someone build a voice chat analyzer that gives real-time communication tips for team games",
        "content": "Toxicity and poor communication ruin team games. Analyze voice chat in real-time, give feedback like 'you interrupted 3 times' or 'suggest strategy instead of blaming'. Improve team coordination.",
        "source": "hackernews",
        "author": "game_psychologist",
        "published_at": (datetime.now() - timedelta(days=11)).isoformat() + "Z",
        "metadata": {
            "upvotes": 234,
            "comments": 156,
            "domain": "gaming",
            "tags": ["gaming", "communication", "ai", "voice-analysis", "teamwork"],
        },
    },
    {
        "url": "https://reddit.com/r/GameDev/comments/gamedev001",
        "title": "I wish there was a tool that analyzes game balance from replay data using ML",
        "content": "Balancing multiplayer games is hard. Upload match replays, let ML find overpowered strategies, underused mechanics, and suggest balance tweaks. Data-driven game design.",
        "source": "reddit",
        "author": "indie_gamedev",
        "published_at": (datetime.now() - timedelta(days=14)).isoformat() + "Z",
        "metadata": {
            "upvotes": 267,
            "comments": 78,
            "domain": "gaming",
            "subreddit": "GameDev",
            "tags": [
                "game-design",
                "balance",
                "machine-learning",
                "analytics",
                "gamedev",
            ],
        },
    },
    {
        "url": "https://twitter.com/streamer_pro/status/1234570004",
        "title": "Need a stream overlay editor that integrates with game events in real-time",
        "content": "Static overlays are boring. I want animations triggered by in-game events: health drops, kills, achievements. Visual programming for stream overlays. No coding required. Works with all games.",
        "source": "twitter",
        "author": "twitch_streamer",
        "published_at": (datetime.now() - timedelta(days=17)).isoformat() + "Z",
        "metadata": {
            "likes": 389,
            "retweets": 112,
            "domain": "gaming",
            "tags": [
                "streaming",
                "overlays",
                "automation",
                "twitch",
                "content-creation",
            ],
        },
    },
    {
        "url": "https://news.ycombinator.com/item?id=39902005",
        "title": "I need a matchmaking platform for finding co-op gaming partners based on playstyle compatibility",
        "content": "Playing with randoms is hit-or-miss. Match me with players who have compatible schedules, communication styles, skill levels, and game preferences. Tinder for gaming buddies.",
        "source": "hackernews",
        "author": "coop_gamer",
        "published_at": (datetime.now() - timedelta(days=20)).isoformat() + "Z",
        "metadata": {
            "upvotes": 412,
            "comments": 145,
            "domain": "gaming",
            "tags": ["gaming", "social", "matchmaking", "multiplayer", "community"],
        },
    },
    # Parenting (6 posts)
    {
        "url": "https://reddit.com/r/Parenting/comments/parent001",
        "title": "Need an app that coordinates childcare schedules between divorced parents with automatic conflict resolution",
        "content": "Co-parenting calendars are chaotic. I want shared custody scheduling, pickup/dropoff reminders, expense tracking, and document storage. When conflicts arise, suggest fair compromises based on history.",
        "source": "reddit",
        "author": "divorced_parent",
        "published_at": (datetime.now() - timedelta(days=8)).isoformat() + "Z",
        "metadata": {
            "upvotes": 567,
            "comments": 234,
            "domain": "parenting",
            "subreddit": "Parenting",
            "tags": [
                "parenting",
                "custody",
                "scheduling",
                "co-parenting",
                "organization",
            ],
        },
    },
    {
        "url": "https://twitter.com/new_parent/status/1234570005",
        "title": "Why isn't there a baby sleep tracker that uses room audio instead of wearables?",
        "content": "Babies hate wearables. Use my phone's mic to detect sleep patterns, crying, and sleep quality. ML-powered sleep coaching. Knows when they're in deep sleep vs light sleep. Privacy-first, local processing.",
        "source": "twitter",
        "author": "tech_parent",
        "published_at": (datetime.now() - timedelta(days=13)).isoformat() + "Z",
        "metadata": {
            "likes": 445,
            "retweets": 123,
            "domain": "parenting",
            "tags": ["parenting", "baby", "sleep", "audio-detection", "ml"],
        },
    },
    {
        "url": "https://news.ycombinator.com/item?id=39902006",
        "title": "Someone build a kid-friendly video call app that detects when they wander off and alerts parents",
        "content": "Video calling grandparents with toddlers is chaos. Use computer vision to detect when the kid leaves the frame, pause the call, send a notification. Resume when they return. Kid-safe, no recording.",
        "source": "hackernews",
        "author": "remote_grandparent",
        "published_at": (datetime.now() - timedelta(days=16)).isoformat() + "Z",
        "metadata": {
            "upvotes": 389,
            "comments": 167,
            "domain": "parenting",
            "tags": ["parenting", "video-calls", "computer-vision", "family", "safety"],
        },
    },
    {
        "url": "https://reddit.com/r/daddit/comments/dad001",
        "title": "I wish there was an app that gamifies chores for kids with a virtual reward system",
        "content": "Sticker charts don't work. I want a mobile app where kids complete chores, earn points, unlock rewards (extra screen time, special treats). Parents control reward catalog. Progress tracking and motivation.",
        "source": "reddit",
        "author": "gamification_dad",
        "published_at": (datetime.now() - timedelta(days=19)).isoformat() + "Z",
        "metadata": {
            "upvotes": 512,
            "comments": 198,
            "domain": "parenting",
            "subreddit": "daddit",
            "tags": ["parenting", "gamification", "chores", "motivation", "rewards"],
        },
    },
    {
        "url": "https://twitter.com/busy_parent/status/1234570006",
        "title": "Need a meal planning app specifically for picky eaters with texture/sensory sensitivities",
        "content": "Generic meal planners don't account for sensory issues. I need recipes filtered by texture (no mushy foods), temperature preferences, and gradual exposure therapy plans. Help expand their palate safely.",
        "source": "twitter",
        "author": "sensory_parent",
        "published_at": (datetime.now() - timedelta(days=22)).isoformat() + "Z",
        "metadata": {
            "likes": 378,
            "retweets": 145,
            "domain": "parenting",
            "tags": [
                "parenting",
                "nutrition",
                "picky-eaters",
                "sensory",
                "meal-planning",
            ],
        },
    },
    {
        "url": "https://news.ycombinator.com/item?id=39902007",
        "title": "I need a pediatric symptom checker that actually knows when to say 'go to the ER'",
        "content": "WebMD makes everything seem fatal. Give me an evidence-based symptom checker trained on pediatric data. Triage: home care vs urgent care vs ER. Saves unnecessary ER visits and catches serious issues early.",
        "source": "hackernews",
        "author": "worried_parent",
        "published_at": (datetime.now() - timedelta(days=25)).isoformat() + "Z",
        "metadata": {
            "upvotes": 678,
            "comments": 289,
            "domain": "parenting",
            "tags": ["parenting", "health", "pediatrics", "symptom-checker", "triage"],
        },
    },
    # Pets (5 posts)
    {
        "url": "https://reddit.com/r/dogs/comments/dog001",
        "title": "Need an app that uses computer vision to analyze my dog's behavior and detect health issues early",
        "content": "Dogs hide pain. Use my phone camera to track gait changes, appetite patterns, lethargy levels, and alert me to potential health problems before they're obvious. Preventive care through AI.",
        "source": "reddit",
        "author": "dog_health_tech",
        "published_at": (datetime.now() - timedelta(days=7)).isoformat() + "Z",
        "metadata": {
            "upvotes": 489,
            "comments": 156,
            "domain": "pets",
            "subreddit": "dogs",
            "tags": ["pets", "health", "computer-vision", "dogs", "ai"],
        },
    },
    {
        "url": "https://twitter.com/cat_owner/status/1234570007",
        "title": "Why isn't there a smart cat litter box that tracks health metrics and predicts vet visits?",
        "content": "Cats are masters of hiding illness. Litter box with sensors: weight changes, urination frequency, stool consistency. ML predicts health issues days before symptoms. Automatic vet alerts.",
        "source": "twitter",
        "author": "cat_tech_enthusiast",
        "published_at": (datetime.now() - timedelta(days=12)).isoformat() + "Z",
        "metadata": {
            "likes": 567,
            "retweets": 189,
            "domain": "pets",
            "tags": ["pets", "health", "iot", "cats", "predictive"],
        },
    },
    {
        "url": "https://news.ycombinator.com/item?id=39902008",
        "title": "Someone build a pet-sitting marketplace with real-time GPS tracking and live video check-ins",
        "content": "Leaving pets with strangers is stressful. I want: verified sitters with reviews, GPS collar integration, scheduled video check-ins, and instant messaging. Peace of mind when traveling.",
        "source": "hackernews",
        "author": "frequent_traveler_pet",
        "published_at": (datetime.now() - timedelta(days=15)).isoformat() + "Z",
        "metadata": {
            "upvotes": 345,
            "comments": 98,
            "domain": "pets",
            "tags": ["pets", "marketplace", "gps", "video", "trust"],
        },
    },
    {
        "url": "https://reddit.com/r/reptiles/comments/reptile001",
        "title": "I wish there was an environmental monitoring system for reptile enclosures with automated adjustments",
        "content": "Reptiles need precise temperature and humidity. Smart sensors that monitor conditions 24/7, automatically adjust heat lamps/misters, alert me to issues, and log data for vet visits. Set-and-forget herpetoculture.",
        "source": "reddit",
        "author": "reptile_keeper",
        "published_at": (datetime.now() - timedelta(days=18)).isoformat() + "Z",
        "metadata": {
            "upvotes": 234,
            "comments": 67,
            "domain": "pets",
            "subreddit": "reptiles",
            "tags": ["pets", "reptiles", "iot", "automation", "monitoring"],
        },
    },
    {
        "url": "https://twitter.com/fish_keeper/status/1234570008",
        "title": "Need an aquarium management app that tracks water parameters and predicts maintenance needs",
        "content": "Tracking water tests manually is tedious. App that logs pH, ammonia, nitrates. Predicts when water changes are needed. Reminds me of filter cleanings. Learns my tank's bioload patterns. Fishkeeping made easy.",
        "source": "twitter",
        "author": "aquarium_hobbyist",
        "published_at": (datetime.now() - timedelta(days=21)).isoformat() + "Z",
        "metadata": {
            "likes": 278,
            "retweets": 89,
            "domain": "pets",
            "tags": ["pets", "aquarium", "water-chemistry", "tracking", "predictive"],
        },
    },
    # Home & Garden (5 posts)
    {
        "url": "https://reddit.com/r/HomeImprovement/comments/home001",
        "title": "Need an app that uses AR to visualize furniture placement and room layouts before buying",
        "content": "Buying furniture online is risky. Use AR to place 3D models in my actual room, check dimensions, see how it looks from different angles. Integration with furniture store catalogs. No more returns!",
        "source": "reddit",
        "author": "interior_designer_diy",
        "published_at": (datetime.now() - timedelta(days=9)).isoformat() + "Z",
        "metadata": {
            "upvotes": 534,
            "comments": 145,
            "domain": "home",
            "subreddit": "HomeImprovement",
            "tags": ["home", "ar", "furniture", "interior-design", "shopping"],
        },
    },
    {
        "url": "https://twitter.com/plant_parent/status/1234570009",
        "title": "Why isn't there a plant care app that uses image recognition to identify issues and suggest treatments?",
        "content": "My plants keep dying and I don't know why. Take a photo, AI identifies the plant, diagnoses problems (overwatering, pests, nutrient deficiency), suggests specific fixes. Preventive care calendar included.",
        "source": "twitter",
        "author": "houseplant_enthusiast",
        "published_at": (datetime.now() - timedelta(days=14)).isoformat() + "Z",
        "metadata": {
            "likes": 612,
            "retweets": 201,
            "domain": "home",
            "tags": ["home", "plants", "image-recognition", "gardening", "ai"],
        },
    },
    {
        "url": "https://news.ycombinator.com/item?id=39902009",
        "title": "Someone build a smart home automation platform that learns from my routines without programming",
        "content": "Home Assistant requires coding. I want a system that observes my patterns (lights on at 7am, thermostat down at 10pm) and automates them. Suggest optimizations. Plain English rules. Works with any device.",
        "source": "hackernews",
        "author": "smart_home_user",
        "published_at": (datetime.now() - timedelta(days=17)).isoformat() + "Z",
        "metadata": {
            "upvotes": 489,
            "comments": 178,
            "domain": "home",
            "tags": ["home", "automation", "iot", "machine-learning", "smart-home"],
        },
    },
    {
        "url": "https://reddit.com/r/DIY/comments/diy001",
        "title": "I wish there was a tool that calculates exact material quantities for DIY projects from photos",
        "content": "Home Depot visits always result in too much or too little material. Upload project photos, get precise measurements, material lists, cost estimates, and where to buy. Computer vision for contractors.",
        "source": "reddit",
        "author": "weekend_warrior_diy",
        "published_at": (datetime.now() - timedelta(days=20)).isoformat() + "Z",
        "metadata": {
            "upvotes": 445,
            "comments": 123,
            "domain": "home",
            "subreddit": "DIY",
            "tags": ["home", "diy", "computer-vision", "estimation", "construction"],
        },
    },
    {
        "url": "https://twitter.com/energy_saver/status/1234570010",
        "title": "Need an energy monitoring app that identifies vampire power drains and suggests specific fixes",
        "content": "My electricity bill is high but I don't know why. Smart plug integration, ML analysis finds energy hogs, calculates ROI on upgrades (LED bulbs, efficient appliances), tracks savings over time. Optimize home energy.",
        "source": "twitter",
        "author": "eco_homeowner",
        "published_at": (datetime.now() - timedelta(days=23)).isoformat() + "Z",
        "metadata": {
            "likes": 389,
            "retweets": 134,
            "domain": "home",
            "tags": ["home", "energy", "iot", "sustainability", "cost-savings"],
        },
    },
    # Career & Professional (6 posts)
    {
        "url": "https://news.ycombinator.com/item?id=39902010",
        "title": "I wish there was a salary negotiation coach app that uses real market data and scripts",
        "content": "Salary negotiation is intimidating. Give me: market data for my role/location, negotiation scripts, practice scenarios with AI, confidence-building exercises, and post-offer analysis. Maximize earnings.",
        "source": "hackernews",
        "author": "career_optimizer",
        "published_at": (datetime.now() - timedelta(days=8)).isoformat() + "Z",
        "metadata": {
            "upvotes": 567,
            "comments": 234,
            "domain": "career",
            "tags": ["career", "salary", "negotiation", "ai", "market-data"],
        },
    },
    {
        "url": "https://reddit.com/r/cscareerquestions/comments/career001",
        "title": "Need a platform that connects junior developers with code review mentors for real projects",
        "content": "Learning to code requires feedback on real projects. Match juniors with experienced devs for paid code reviews, pair programming sessions, architecture discussions. Structured mentorship with clear outcomes.",
        "source": "reddit",
        "author": "junior_dev_seeking_growth",
        "published_at": (datetime.now() - timedelta(days=13)).isoformat() + "Z",
        "metadata": {
            "upvotes": 789,
            "comments": 256,
            "domain": "career",
            "subreddit": "cscareerquestions",
            "tags": ["career", "mentorship", "code-review", "learning", "programming"],
        },
    },
    {
        "url": "https://twitter.com/freelancer_life/status/1234570011",
        "title": "Why isn't there an invoice tracking system that predicts cash flow and alerts to late payments automatically?",
        "content": "Freelancing cash flow is unpredictable. Track invoices, predict when payments arrive based on client history, auto-send payment reminders, integrate with accounting. Financial stability for solopreneurs.",
        "source": "twitter",
        "author": "freelance_consultant",
        "published_at": (datetime.now() - timedelta(days=16)).isoformat() + "Z",
        "metadata": {
            "likes": 445,
            "retweets": 167,
            "domain": "career",
            "tags": ["career", "freelancing", "invoicing", "cash-flow", "automation"],
        },
    },
    {
        "url": "https://news.ycombinator.com/item?id=39902011",
        "title": "Someone build a meeting notes app that generates action items and assigns them during the call",
        "content": "Meeting notes are wasted if nothing happens. Real-time transcription, AI extracts action items, asks participants to confirm ownership, creates calendar events, follows up if incomplete. Meetings that actually produce results.",
        "source": "hackernews",
        "author": "productivity_manager",
        "published_at": (datetime.now() - timedelta(days=19)).isoformat() + "Z",
        "metadata": {
            "upvotes": 678,
            "comments": 201,
            "domain": "career",
            "tags": ["career", "productivity", "meetings", "ai", "transcription"],
        },
    },
    {
        "url": "https://reddit.com/r/Entrepreneur/comments/biz001",
        "title": "I wish there was a platform that validates startup ideas using real search data and trends",
        "content": "Most startups fail because there's no demand. Analyze Google Trends, keyword search volume, competitor analysis, and market growth. Give me a 'viability score' before I spend 6 months building. Data-driven validation.",
        "source": "reddit",
        "author": "aspiring_founder",
        "published_at": (datetime.now() - timedelta(days=22)).isoformat() + "Z",
        "metadata": {
            "upvotes": 912,
            "comments": 345,
            "domain": "career",
            "subreddit": "Entrepreneur",
            "tags": ["career", "startups", "validation", "market-research", "data"],
        },
    },
    {
        "url": "https://twitter.com/remote_worker/status/1234570012",
        "title": "Need a time zone coordination tool that finds optimal meeting times for global teams and respects work-life balance",
        "content": "Scheduling across 8 time zones is hell. Find overlap windows, respect work hours (no 11pm meetings), suggest asynchronous alternatives when no good time exists. Calendar integration, respect cultural holidays.",
        "source": "twitter",
        "author": "distributed_team_lead",
        "published_at": (datetime.now() - timedelta(days=25)).isoformat() + "Z",
        "metadata": {
            "likes": 534,
            "retweets": 189,
            "domain": "career",
            "tags": [
                "career",
                "remote-work",
                "scheduling",
                "time-zones",
                "collaboration",
            ],
        },
    },
    # Mental Health & Wellness (5 posts)
    {
        "url": "https://reddit.com/r/Anxiety/comments/anxiety001",
        "title": "Need an app that detects panic attacks early using heart rate variability and guides breathing exercises",
        "content": "Panic attacks come suddenly. Use smartwatch HRV data to detect early signs, immediately start guided breathing, grounding exercises, and alert emergency contacts if it escalates. Preventive intervention.",
        "source": "reddit",
        "author": "anxiety_warrior",
        "published_at": (datetime.now() - timedelta(days=10)).isoformat() + "Z",
        "metadata": {
            "upvotes": 678,
            "comments": 234,
            "domain": "mental-health",
            "subreddit": "Anxiety",
            "tags": [
                "mental-health",
                "anxiety",
                "wearables",
                "breathing",
                "intervention",
            ],
        },
    },
    {
        "url": "https://twitter.com/therapist_tech/status/1234570013",
        "title": "Why isn't there a journaling app that uses sentiment analysis to track mental health trends over time?",
        "content": "Traditional journals don't show patterns. AI analyzes my entries, tracks mood trends, identifies triggers, suggests coping strategies, alerts me when patterns indicate I should see my therapist. Data-driven mental health.",
        "source": "twitter",
        "author": "mental_health_advocate",
        "published_at": (datetime.now() - timedelta(days=15)).isoformat() + "Z",
        "metadata": {
            "likes": 789,
            "retweets": 267,
            "domain": "mental-health",
            "tags": [
                "mental-health",
                "journaling",
                "sentiment-analysis",
                "ai",
                "self-care",
            ],
        },
    },
    {
        "url": "https://news.ycombinator.com/item?id=39902012",
        "title": "Someone build a meditation app that adapts to my brain state using EEG data in real-time",
        "content": "Generic meditation tracks don't work for everyone. Use consumer EEG headset, detect when my mind wanders, adjust guidance in real-time. Personalized sessions that actually achieve flow state. Biofeedback meditation.",
        "source": "hackernews",
        "author": "neurofeedback_enthusiast",
        "published_at": (datetime.now() - timedelta(days=20)).isoformat() + "Z",
        "metadata": {
            "upvotes": 456,
            "comments": 178,
            "domain": "mental-health",
            "tags": [
                "mental-health",
                "meditation",
                "eeg",
                "biofeedback",
                "neuroscience",
            ],
        },
    },
    {
        "url": "https://reddit.com/r/depression/comments/depression001",
        "title": "I wish there was a mood tracking app that correlates with activity data to identify what actually helps",
        "content": "I don't know what improves my mood. Track mood multiple times daily, correlate with exercise, sleep, social contact, weather, diet. Show me evidence-based insights: 'You're 60% happier on days you exercise before 10am'.",
        "source": "reddit",
        "author": "data_driven_recovery",
        "published_at": (datetime.now() - timedelta(days=24)).isoformat() + "Z",
        "metadata": {
            "upvotes": 845,
            "comments": 289,
            "domain": "mental-health",
            "subreddit": "depression",
            "tags": [
                "mental-health",
                "mood-tracking",
                "data-analysis",
                "correlation",
                "self-improvement",
            ],
        },
    },
    {
        "url": "https://twitter.com/burnout_prevent/status/1234570014",
        "title": "Need a burnout prevention tool that monitors work patterns and enforces breaks before it's too late",
        "content": "Burnout creeps up slowly. Monitor: work hours, email volume, meeting density, time between breaks. Predict burnout risk, enforce mandatory breaks, suggest vacation time, alert manager if patterns are unsustainable.",
        "source": "twitter",
        "author": "worklife_balance_coach",
        "published_at": (datetime.now() - timedelta(days=26)).isoformat() + "Z",
        "metadata": {
            "likes": 912,
            "retweets": 334,
            "domain": "mental-health",
            "tags": [
                "mental-health",
                "burnout",
                "work-life-balance",
                "predictive",
                "prevention",
            ],
        },
    },
    # Learning & Education (5 posts)
    {
        "url": "https://news.ycombinator.com/item?id=39902013",
        "title": "I wish there was a language learning app that creates personalized content from my actual interests",
        "content": "Generic lessons bore me. Scrape articles/videos about topics I care about (tech, cycling, cooking), adapt to my level, generate exercises, track vocabulary. Learn Spanish through content I'd read anyway.",
        "source": "hackernews",
        "author": "polyglot_learner",
        "published_at": (datetime.now() - timedelta(days=11)).isoformat() + "Z",
        "metadata": {
            "upvotes": 734,
            "comments": 198,
            "domain": "education",
            "tags": [
                "education",
                "language-learning",
                "personalization",
                "content",
                "ai",
            ],
        },
    },
    {
        "url": "https://reddit.com/r/GetStudying/comments/study001",
        "title": "Need a spaced repetition system that automatically extracts flashcards from my lecture notes and PDFs",
        "content": "Creating flashcards manually takes forever. Upload notes/PDFs, AI extracts key concepts, generates front/back, optimizes review schedule. Integration with Anki. Study smarter, not harder.",
        "source": "reddit",
        "author": "med_student_efficient",
        "published_at": (datetime.now() - timedelta(days=16)).isoformat() + "Z",
        "metadata": {
            "upvotes": 623,
            "comments": 167,
            "domain": "education",
            "subreddit": "GetStudying",
            "tags": ["education", "studying", "spaced-repetition", "ai", "automation"],
        },
    },
    {
        "url": "https://twitter.com/online_teacher/status/1234570015",
        "title": "Why isn't there a virtual classroom that uses eye-tracking to detect when students are confused and adapts pace?",
        "content": "Online teaching loses real-time feedback. Use webcam eye-tracking: detect confusion (prolonged staring), disengagement (looking away), understanding (nodding). Slow down, repeat, or skip ahead automatically.",
        "source": "twitter",
        "author": "edtech_innovator",
        "published_at": (datetime.now() - timedelta(days=21)).isoformat() + "Z",
        "metadata": {
            "likes": 445,
            "retweets": 156,
            "domain": "education",
            "tags": [
                "education",
                "online-learning",
                "eye-tracking",
                "adaptive",
                "engagement",
            ],
        },
    },
    {
        "url": "https://news.ycombinator.com/item?id=39902014",
        "title": "Someone build a code learning platform that generates personalized practice problems from GitHub repos",
        "content": "Coding tutorials are generic. Analyze my GitHub, identify weak areas, generate targeted practice problems in my tech stack. Real-world scenarios. Difficulty adapts. Level up specific skills, not generic tutorials.",
        "source": "hackernews",
        "author": "self_taught_developer",
        "published_at": (datetime.now() - timedelta(days=23)).isoformat() + "Z",
        "metadata": {
            "upvotes": 867,
            "comments": 245,
            "domain": "education",
            "tags": [
                "education",
                "programming",
                "personalization",
                "practice",
                "github",
            ],
        },
    },
    {
        "url": "https://reddit.com/r/Teachers/comments/teach001",
        "title": "I wish there was a grading assistant that uses AI to provide detailed feedback on essay assignments at scale",
        "content": "Grading 150 essays takes forever. AI reads submissions, checks grammar/style, provides substantive feedback on argument quality, suggests improvements. Teachers review and adjust. Save hours, help students more.",
        "source": "reddit",
        "author": "high_school_teacher",
        "published_at": (datetime.now() - timedelta(days=27)).isoformat() + "Z",
        "metadata": {
            "upvotes": 712,
            "comments": 289,
            "domain": "education",
            "subreddit": "Teachers",
            "tags": ["education", "grading", "ai", "feedback", "automation"],
        },
    },
    # Finance & Investing (5 posts)
    {
        "url": "https://reddit.com/r/personalfinance/comments/finance001",
        "title": "Need an app that analyzes my spending and automatically finds me better deals on recurring subscriptions",
        "content": "I'm wasting money on subscriptions I barely use. Scan transactions, identify recurring charges, find cheaper alternatives or cancelation options. Negotiate bills automatically. Subscription spending optimizer.",
        "source": "reddit",
        "author": "frugal_optimizer",
        "published_at": (datetime.now() - timedelta(days=12)).isoformat() + "Z",
        "metadata": {
            "upvotes": 891,
            "comments": 267,
            "domain": "finance",
            "subreddit": "personalfinance",
            "tags": [
                "finance",
                "subscriptions",
                "savings",
                "automation",
                "optimization",
            ],
        },
    },
    {
        "url": "https://twitter.com/invest_smart/status/1234570016",
        "title": "Why isn't there a tax-loss harvesting tool that works for crypto and alerts to wash sale risks?",
        "content": "Crypto taxes are complex. Automatic tax-loss harvesting, wash sale detection, optimal timing suggestions, cross-exchange tracking. Generate IRS-compliant reports. Save thousands on taxes legally.",
        "source": "twitter",
        "author": "crypto_tax_pro",
        "published_at": (datetime.now() - timedelta(days=17)).isoformat() + "Z",
        "metadata": {
            "likes": 534,
            "retweets": 178,
            "domain": "finance",
            "tags": ["finance", "crypto", "taxes", "automation", "optimization"],
        },
    },
    {
        "url": "https://news.ycombinator.com/item?id=39902015",
        "title": "Someone build a retirement calculator that uses Monte Carlo simulation and adjusts for real-time market conditions",
        "content": "Static retirement calculators are useless. Run thousands of simulations with different market scenarios, adjust assumptions as I update my portfolio, show probability of success. Dynamic retirement planning.",
        "source": "hackernews",
        "author": "retirement_planner",
        "published_at": (datetime.now() - timedelta(days=22)).isoformat() + "Z",
        "metadata": {
            "upvotes": 623,
            "comments": 201,
            "domain": "finance",
            "tags": ["finance", "retirement", "monte-carlo", "planning", "simulation"],
        },
    },
    {
        "url": "https://reddit.com/r/investing/comments/invest001",
        "title": "I wish there was a portfolio rebalancing tool that minimizes taxes while maintaining target allocation",
        "content": "Rebalancing triggers capital gains. Optimize: sell high-loss positions first, use new contributions, respect tax brackets, account for dividend timing. Tax-efficient rebalancing with clear trade recommendations.",
        "source": "reddit",
        "author": "tax_efficient_investor",
        "published_at": (datetime.now() - timedelta(days=25)).isoformat() + "Z",
        "metadata": {
            "upvotes": 734,
            "comments": 189,
            "domain": "finance",
            "subreddit": "investing",
            "tags": ["finance", "investing", "taxes", "rebalancing", "optimization"],
        },
    },
    {
        "url": "https://twitter.com/budget_guru/status/1234570017",
        "title": "Need a bill negotiation service that uses AI to call and negotiate lower rates on my behalf",
        "content": "Negotiating bills is time-consuming. AI agent calls my providers (internet, insurance, phone), negotiates using market data and competitor offers, secures discounts. Pay only if I save money. Automated savings.",
        "source": "twitter",
        "author": "savings_hacker",
        "published_at": (datetime.now() - timedelta(days=28)).isoformat() + "Z",
        "metadata": {
            "likes": 845,
            "retweets": 289,
            "domain": "finance",
            "tags": ["finance", "negotiation", "ai", "automation", "savings"],
        },
    },
    # Travel (5 posts)
    {
        "url": "https://reddit.com/r/travel/comments/travel001",
        "title": "Need a flight deal finder that learns my preferences and alerts me proactively to good deals",
        "content": "I miss great flight deals because I'm not constantly checking. ML learns my travel patterns (destinations, dates, budget), monitors prices, alerts only when it's a genuinely good deal for MY criteria. Smart travel alerts.",
        "source": "reddit",
        "author": "frequent_flyer_deals",
        "published_at": (datetime.now() - timedelta(days=14)).isoformat() + "Z",
        "metadata": {
            "upvotes": 712,
            "comments": 198,
            "domain": "travel",
            "subreddit": "travel",
            "tags": ["travel", "flights", "deals", "machine-learning", "alerts"],
        },
    },
    {
        "url": "https://twitter.com/digital_nomad/status/1234570018",
        "title": "Why isn't there a co-living matchmaking platform that finds compatible roommates for digital nomads?",
        "content": "Finding short-term housing with compatible people is hard. Match by work schedule, cleanliness, social preferences, hobbies. Verified profiles, reviews, contract templates. Airbnb meets compatibility matching for nomads.",
        "source": "twitter",
        "author": "nomad_community_builder",
        "published_at": (datetime.now() - timedelta(days=19)).isoformat() + "Z",
        "metadata": {
            "likes": 567,
            "retweets": 201,
            "domain": "travel",
            "tags": ["travel", "nomad", "co-living", "matchmaking", "community"],
        },
    },
    {
        "url": "https://news.ycombinator.com/item?id=39902016",
        "title": "Someone build a trip planning app that optimizes multi-city itineraries for cost and experience",
        "content": "Planning complex trips is overwhelming. Input destinations and dates, AI optimizes: flight routing, hotel locations, activity timing. Considers jet lag, opening hours, crowd levels. One-click book entire optimized itinerary.",
        "source": "hackernews",
        "author": "trip_optimizer",
        "published_at": (datetime.now() - timedelta(days=23)).isoformat() + "Z",
        "metadata": {
            "upvotes": 623,
            "comments": 178,
            "domain": "travel",
            "tags": ["travel", "planning", "optimization", "ai", "itinerary"],
        },
    },
    {
        "url": "https://reddit.com/r/solotravel/comments/solo001",
        "title": "I wish there was a safety app for solo travelers that shares location and checks in automatically",
        "content": "Solo travel can feel unsafe. Automatic check-ins at key points, emergency contacts get alerts if I don't check in, live location sharing during risky activities. Peace of mind for me and family back home.",
        "source": "reddit",
        "author": "solo_female_traveler",
        "published_at": (datetime.now() - timedelta(days=26)).isoformat() + "Z",
        "metadata": {
            "upvotes": 834,
            "comments": 245,
            "domain": "travel",
            "subreddit": "solotravel",
            "tags": ["travel", "safety", "location-sharing", "check-in", "solo"],
        },
    },
    {
        "url": "https://twitter.com/travel_hacker/status/1234570019",
        "title": "Need a luggage packing assistant that generates optimal packing lists based on destination weather and activities",
        "content": "I always forget something or overpack. Input destination/dates/activities, get weather-optimized packing list, outfit combinations, toiletry reminders. Learn from past trips. Never forget essentials again.",
        "source": "twitter",
        "author": "organized_traveler",
        "published_at": (datetime.now() - timedelta(days=29)).isoformat() + "Z",
        "metadata": {
            "likes": 489,
            "retweets": 167,
            "domain": "travel",
            "tags": ["travel", "packing", "weather", "organization", "planning"],
        },
    },
]

# Save expanded data
output_file = "sample_posts_expanded.json"
with open(output_file, "w", encoding="utf-8") as f:
    json.dump(new_posts, f, indent=2, ensure_ascii=False)

print(f"✅ Generated {len(new_posts)} new posts")
print(f"📁 Saved to {output_file}")
print(
    f"📊 Domains covered: {len(set(post['metadata']['domain'] for post in new_posts))}"
)
print("\nNext: Merge with existing sample_posts.json manually or replace entirely.")
